//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplyTravelDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Remainders = new HashSet<Remainders>();
            this.Trips = new HashSet<Trips>();
        }
    
        public int idCustomer { get; set; }
        public string passwordCustomer { get; set; }
        public string checkPassword { get; set; }
        public string email { get; set; }
        public string nameCustomer { get; set; }
        public Nullable<int> extraLevel { get; set; }
        public Nullable<bool> free_notFree { get; set; }
        public Nullable<int> sumToPay { get; set; }
        public Nullable<int> minAge { get; set; }
        public Nullable<int> maxAge { get; set; }
        public Nullable<bool> car_bus { get; set; }
        public string statusCustomer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remainders> Remainders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trips> Trips { get; set; }
    }
}
