//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplyTravelDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimplyTravelEntitiesNew : DbContext
    {
        public SimplyTravelEntitiesNew()
            : base("name=SimplyTravelEntitiesNew")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<Remainders> Remainders { get; set; }
        public virtual DbSet<Responses> Responses { get; set; }
        public virtual DbSet<Sites> Sites { get; set; }
        public virtual DbSet<SitesInTrip> SitesInTrip { get; set; }
        public virtual DbSet<SitesKind> SitesKind { get; set; }
        public virtual DbSet<Sub_Regions> Sub_Regions { get; set; }
        public virtual DbSet<Trips> Trips { get; set; }
    }
}
