//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplyTravelDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remainders
    {
        public int codeRemainder { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public string describe { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
