//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplyTravelDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responses
    {
        public int codeResponse { get; set; }
        public Nullable<int> codeSiteInTrip { get; set; }
        public Nullable<int> question1 { get; set; }
        public Nullable<int> question2 { get; set; }
        public Nullable<int> question3 { get; set; }
        public Nullable<int> question4 { get; set; }
        public Nullable<int> question5 { get; set; }
        public string notes { get; set; }
    
        public virtual SitesInTrip SitesInTrip { get; set; }
    }
}
