//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplyTravelDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitesInTrip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SitesInTrip()
        {
            this.Responses = new HashSet<Responses>();
        }
    
        public int codeSiteInTrip { get; set; }
        public Nullable<int> codeTrip { get; set; }
        public Nullable<int> codeSite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Responses> Responses { get; set; }
        public virtual Sites Sites { get; set; }
        public virtual Trips Trips { get; set; }
    }
}
