//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplyTravelDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sites()
        {
            this.SitesInTrip = new HashSet<SitesInTrip>();
        }
    
        public int codeSite { get; set; }
        public Nullable<int> codeSiteKind { get; set; }
        public string nameSite { get; set; }
        public string adress { get; set; }
        public Nullable<int> codeSub_Region { get; set; }
        public Nullable<int> extraLevel { get; set; }
        public Nullable<int> minAge { get; set; }
        public Nullable<int> maxAge { get; set; }
        public Nullable<int> misLiterWater { get; set; }
        public Nullable<bool> free_notFree { get; set; }
        public Nullable<int> sumToPay { get; set; }
        public Nullable<bool> car_bus { get; set; }
        public string coordination { get; set; }
        public Nullable<double> timeSpend { get; set; }
        public string statusSite { get; set; }
    
        public virtual SitesKind SitesKind { get; set; }
        public virtual Sub_Regions Sub_Regions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitesInTrip> SitesInTrip { get; set; }
    }
}
